### PR TITLE
chore: try embed trick to include non-go files on vendor

### PR DESCRIPTION
**Pull request by markphelps**
try to fix: #558

### CODE REVIEW

**Review by nhunam — APPROVED** [review]
LGTM

**Review by GeorgeMac — COMMENTED** [review]
Nice hack. Do we need to do the same for the other non go files?

seems like we will run into this with the dynamic libs too?

Shame we have to then also add all these objects to any resulting binaries in another location in memory for everyone just to make this work 😮‍💨

**Review by erka — CHANGES_REQUESTED** [review]
this doesn't work :(

**Comment by markphelps** [comment]
> this doesn't work :(
> 
> `ext.go` should be in `evaluation` package with
> 
> ```go
> package evaluation 
> 
> import "embed"
> 
> //go:embed ext/*
> var _ embed.FS
> ```

is this because we need to fake embed the libraries too for vendoring? i hope this doesn't make the filesize double in the archive

**Comment by erka** [comment]
@markphelps I tried the local app with vendor vs shared deps and the binary size was the same. It would be nice to have a deeper knowledge about this situation.

**Review by erka — APPROVED** [review]

**Comment by markphelps** [comment]
So this is interesting.. it now packages both libc folders in `/ext` and includes them in the archive:

CleanShot 2024-12-06 at 12 43 57

This might actually allow us to implement what is asked for in https://github.com/flipt-io/flipt-client-sdks/issues/141#issuecomment-2469360866 by using buildtags to for the appropriate arch. It still would mean that the initial `go get` would be like 30mb transfered though, but it would only include the needed lib in the actual build of the consuming binary

**Comment by markphelps** [comment]
also its just plain wrong as windows and darwin shouldn't have musl versions.. something odd is going on with the packaging now

**Comment by markphelps** [comment]
ok so i removed the `ext.go` embed and published a new release and can verify the packaging issue is not related to the `ext.go` change, there is something else wrong with our packaging workflow that I'll need to fix first

**Pull request merged**
