### PR TITLE
refactor!(go):  hide result types from go-sdk

### PR DESCRIPTION
**Pull request by erka**
related #353

### CODE REVIEW

**Comment by erka** [comment]
>  can we rename `EngineOpts` to `ClientOptions` like in [73a1d84](https://github.com/flipt-io/flipt-client-sdks/commit/73a1d84a0f7c9c18fda4d031a84145a533a8c1a3)
> 
> ```
> engOpts := &EngineOpts[any]{
> 		URL:            client.url,
> 		UpdateInterval: client.updateInterval,
> 		Authentication: &client.authentication,
> 		Reference:      client.ref,
> 	}
> ```
> 

@markphelps I'd appreciate it if we could verify this. I'm thinking that `EngineOpts` should not be exposed publicly since it's only used internally within the system. Additionally, are go `clientOption` and node `ClientOptions` actually equivalent in terms of their definition at this specific commit?

**Comment by markphelps** [comment]
> > can we rename `EngineOpts` to `ClientOptions` like in [73a1d84](https://github.com/flipt-io/flipt-client-sdks/commit/73a1d84a0f7c9c18fda4d031a84145a533a8c1a3)
> > ```
> > engOpts := &EngineOpts[any]{
> > 		URL:            client.url,
> > 		UpdateInterval: client.updateInterval,
> > 		Authentication: &client.authentication,
> > 		Reference:      client.ref,
> > 	}
> > ```
> 
> @markphelps I'd appreciate it if we could verify this. I'm thinking that `EngineOpts` should not be exposed publicly since it's only used internally within the system. Additionally, are go `clientOption` and node `ClientOptions` actually equivalent in terms of their definition at this specific commit?

Oh yeah you're right. I forgot we only expose functional options for configuring the client. 

I do think we could still rename `Client` to `FliptEvaluationClient` though, wdty?

**Comment by erka** [comment]
> I do think we could still rename `Client` to `FliptEvaluationClient` though, wdty?

This is a challenging question. I believe we should not use the same name across all clients because some languages have package name in front. For example, in Go and Ruby I would prefer `EvaluationClient`, so it could be as `flipt.EvaluationClient` in Go or `Flipt::EvaluationClient` in Ruby.  I don't like double the same word twice.  wdyt?

**Review by markphelps — APPROVED** [review]
awesome! ty

**Pull request merged**
