### PR TITLE
chore: make evaluation lib code and evaluation response types more idiomatic

### PR DESCRIPTION
**Pull request by markphelps**
brought to you by AI

this will actually be a breaking change for Java and Python SDKs as it changes `variant_key` and `variant_attachment` fields to be Optional 

I think we should use Optional where relevant for those languages that support it

### CODE REVIEW

**Review by GeorgeMac — APPROVED** [review]
Thank you robots

**Comment by erka** [comment]
Will this also conflict with the GRPC schema of the Flipt API? Those fields are `string` without `optional` modifier. wdyt?

**Comment by markphelps** [comment]
I'm also OK with not doing the optional changes right now though if we think it would make for an awkward experience / upgrade

**Comment by erka** [comment]
> I'm also OK with not doing the optional changes right now though if we think it would make for an awkward experience / upgrade

Maybe the `optional` is correct thing but it creates inconsistency in the  Flipt API for current version imho.

**Comment by markphelps** [comment]
> > I'm also OK with not doing the optional changes right now though if we think it would make for an awkward experience / upgrade
> 
> Maybe the `optional` is correct thing but it creates inconsistency in the Flipt API for current version imho.

Yeah I can revert those bits and just leave a comment that we should/could make them optional in the future but would be breaking API

**Review by erka — APPROVED** [review]

**Pull request merged**
